global:
  cattle:
    url: https://rancher.10.7.2.222.nip.io
neuvector:
  controller:
    pvc:
      enabled: false
    ranchersso:
      enabled: true
    runAsUser: 1000
  global:
    cattle:
      url: https://rancher.10.7.2.222.nip.io
  k3s:
    enabled: true
    runtimePath: /run/k3s/containerd/containerd.sock
  manager:
    svc:
      type: ClusterIP
    ingress:
      enabled: true
      host: neuvector-manager.10.7.2.222.nip.io
    runAsUser: 1000
  controller:
    apisvc:
      type: ClusterIP
    ingress:
      enabled: true
      host: neuvector-controller.10.7.2.222.nip.io
    federation:
      managedsvc:
        type: ClusterIP
        ingress:
          enabled: true
          host: neuvector-fed-managed.10.7.2.222.nip.io
  enforcer:
    runAsUser: 1000
  cve:
    scanner:
      runAsUser: 1000
    updater:
      runAsUser: 1000
  rbac: true
  leastPrivilege: true
